baseURL = 'https://vladmueller.de'
languageCode = 'en-us'
title = 'Vladimir Müller'
theme = 'archie'
copyright = "© Vladimir Müller"

[params]
mode = "auto"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vladmueller"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://example.com/linkedin"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 4
