name: Deploy Blog to Uberspace
on:
  push:
    branches: [main, deploy, draft]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true' # Fetch Hugo themes

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: 'true'

      - name: Build website with Hugo
        run: hugo --minify -D

      - name: Set Remote Path
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/draft" ]]; then
            echo "REMOTE_PATH=/var/www/virtual/${{ vars.SSH_USERNAME }}/draft.vladmueller.de" >> $GITHUB_ENV
          else
            echo "REMOTE_PATH=/var/www/virtual/${{ vars.SSH_USERNAME }}/vladmueller.de" >> $GITHUB_ENV
          fi

      - name: Deploy using rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete --exclude=".htaccess"
          path: ./public/
          remote_path: ${{ env.REMOTE_PATH }}
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASS }} # Only needed if you added a passphrase upon creating the SSH key
